version: '3.9'

services:
  db:
    image: postgres:16
    container_name: db-container
    environment:
      - POSTGRES_USER=kamivision
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_db
    ports:
      - "5433:5432"
  backend:
    build: ./server
    container_name: django-container
    command: sh -c "gunicorn task_api.wsgi --bind 0.0.0.0:8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db
    